<div class="mb-3">
    <label class="form-label">Rechte</label>
    <p class="text-muted small mb-2">Diese Rechte werden als Vorlage genutzt und können beim Benutzer individuell angepasst werden.</p>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_reservations" id="add_role_can_reservations"><label class="form-check-label" for="add_role_can_reservations">Reservierungen</label> <input class="form-check-input ms-3" type="checkbox" name="role_can_reservations_readonly" id="add_role_can_reservations_readonly"><label class="form-check-label ms-1" for="add_role_can_reservations_readonly">Nur Leserechte</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_atemschutz" id="add_role_can_atemschutz"><label class="form-check-label" for="add_role_can_atemschutz">Atemschutz</label> <input class="form-check-input ms-3" type="checkbox" name="role_can_atemschutz_readonly" id="add_role_can_atemschutz_readonly"><label class="form-check-label ms-1" for="add_role_can_atemschutz_readonly">Nur Leserechte</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_members" id="add_role_can_members"><label class="form-check-label" for="add_role_can_members">Mitgliederverwaltung</label> <input class="form-check-input ms-3" type="checkbox" name="role_can_members_readonly" id="add_role_can_members_readonly"><label class="form-check-label ms-1" for="add_role_can_members_readonly">Nur Leserechte</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_ric" id="add_role_can_ric"><label class="form-check-label" for="add_role_can_ric">RIC</label> <input class="form-check-input ms-3" type="checkbox" name="role_can_ric_readonly" id="add_role_can_ric_readonly"><label class="form-check-label ms-1" for="add_role_can_ric_readonly">Nur Leserechte</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_courses" id="add_role_can_courses"><label class="form-check-label" for="add_role_can_courses">Lehrgänge</label> <input class="form-check-input ms-3" type="checkbox" name="role_can_courses_readonly" id="add_role_can_courses_readonly"><label class="form-check-label ms-1" for="add_role_can_courses_readonly">Nur Leserechte</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_auswertung" id="add_role_can_auswertung"><label class="form-check-label" for="add_role_can_auswertung">Auswertung</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_forms_fill" id="add_role_can_forms_fill"><label class="form-check-label" for="add_role_can_forms_fill">Formulare ausfüllen</label></div>
    <div class="form-check"><input class="form-check-input" type="checkbox" name="role_can_forms" id="add_role_can_forms"><label class="form-check-label" for="add_role_can_forms">Formularcenter</label> <input class="form-check-input ms-3" type="checkbox" name="role_can_forms_readonly" id="add_role_can_forms_readonly"><label class="form-check-label ms-1" for="add_role_can_forms_readonly">Nur Leserechte</label></div>
</div>
